name: Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push with tags
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compress the map folder
        run: |
          cd map
          zip -r ../cnet_map.zip .
          cd ..

      - name: Compress the Web client
        run: | 
          zip -r web_client.zip ./web_client/*
          cd ..
        
      - name: Upload cnet_map artifact
        uses: actions/upload-artifact@v4
        with:
          name: cnet_map
          path: ./cnet_map.zip
        
      - name: Upload web_client artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_client
          path: ./web_client.zip
  
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cnet_map.zip, web_client.zip, DashboardGrafana.json"
