# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Compress the map folder
        run: |
          cd map
          zip -r ../cnet_map.zip .
        
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: cnet_map
          path: ./cnet_map.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cnet_map.zip"
